# -------------------------------------------------------------------
# - DOCKER COMPOSE FILE
# - AUTOR: Equipo 5
# - FECHA: 20-Abril-2020
# - DESCRIPCION: Docker compose file que permite la
# -              creacion de un contenedor con el servicio de emails
# -------------------------------------------------------------------

version: '3.7'
services:
  notifications-service:
    image: wortiz1027/notifications-service:latest
    container_name: notifications-service
    hostname: notifications-service
    restart: always
    ports:
      - 8093:8093
      - 6093:6093
    environment:  
      - CONFIG_SERVER=http://10.39.1.85:9090
      - EUREKA_SERVER=http://10.39.1.85:9091/eureka
      - EUREKA_HOST=10.39.1.85
      - RABBITMQ_HOST=10.39.1.85
      - SERVICE_PORTS=8093
    networks:
      - ntw_backend

volumes:
  data_convenios:
networks:
  ntw_backend:
    external: true
